### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by Branko-Dj** [datasets/openml-datasets#1]
Some datasets when uploaded to datahub have validation errors
## Acceptance criteria
- [ ] All validation errors are removed for all datasets

## Tasks
- [ ] Find all datasets with validation errors (example: https://datahub.io/machine-learning/creditcard)
- [ ] Fix validation errors
